-- ============================================================================
--  cv-engine-worker / sql / expanded-seed-v2.sql
--  AUTO-GENERATED from attached_assets/Pasted--CV-Engine-EXPANDED-Seed-Data-v2-…
--  Do NOT edit by hand — re-run scripts/extract-expanded-seed-v2.cjs instead.
--
--  Idempotent:
--    • every INSERT is rewritten as INSERT OR IGNORE
--    • DELETE FROM lines from the source are stripped (we never wipe existing data)
--    • SQL-level UNIQUE indexes on each cv_* table dedupe re-runs
--
--  Apply with: node cv-engine-worker/scripts/apply-sql-file.cjs sql/expanded-seed-v2.sql
--  Then KV-sync with: npm --prefix cv-engine-worker run kv:sync
-- ============================================================================

-- ─── block 1/6 ────────────────────────────────
-- ============================================
-- TECHNICAL — GENERAL ENGINEERING (60 verbs)
-- ============================================
INSERT OR IGNORE INTO cv_verbs (verb_present, verb_past, category, energy_level, human_score, industry) VALUES
('Designs','Designed','technical','high',9,'general'),
('Builds','Built','technical','high',9,'general'),
('Implements','Implemented','technical','high',9,'general'),
('Engineers','Engineered','technical','high',9,'general'),
('Develops','Developed','technical','high',9,'general'),
('Deploys','Deployed','technical','high',9,'general'),
('Installs','Installed','technical','high',8,'general'),
('Configures','Configured','technical','high',8,'general'),
('Architects','Architected','technical','high',8,'general'),
('Constructs','Constructed','technical','high',8,'general'),
('Fabricates','Fabricated','technical','high',8,'general'),
('Repairs','Repaired','technical','high',8,'general'),
('Upgrades','Upgraded','technical','high',8,'general'),
('Overhauls','Overhauled','technical','high',8,'general'),
('Automates','Automated','technical','high',8,'general'),
('Integrates','Integrated','technical','high',8,'general'),
('Optimizes','Optimized','technical','high',8,'general'),
('Refactors','Refactored','technical','high',8,'general'),
('Calibrates','Calibrated','technical','medium',8,'general'),
('Commissions','Commissioned','technical','medium',8,'general'),
('Troubleshoots','Troubleshot','technical','medium',8,'general'),
('Maintains','Maintained','technical','medium',8,'general'),
('Inspects','Inspected','technical','medium',8,'general'),
('Tests','Tested','technical','medium',8,'general'),
('Validates','Validated','technical','medium',8,'general'),
('Verifies','Verified','technical','medium',8,'general'),
('Diagnoses','Diagnosed','technical','high',8,'general'),
('Retrofits','Retrofitted','technical','medium',7,'general'),
('Modifies','Modified','technical','medium',7,'general'),
('Assembles','Assembled','technical','medium',7,'general'),
('Operates','Operated','technical','medium',7,'general'),
('Converts','Converted','technical','medium',7,'general'),
('Rectifies','Rectified','technical','medium',7,'general'),
('Regulates','Regulated','technical','medium',7,'general'),
('Restores','Restored','technical','medium',7,'general'),
('Standardizes','Standardized','technical','medium',8,'general'),
('Systematizes','Systematized','technical','medium',7,'general'),
('Computes','Computed','technical','medium',7,'general'),
('Solves','Solved','technical','high',8,'general'),
('Remodels','Remodeled','technical','medium',7,'general'),
('Strengthens','Strengthened','technical','medium',7,'general'),
('Stabilizes','Stabilized','technical','medium',7,'general'),
('Reinforces','Reinforced','technical','medium',7,'general'),
('Adapts','Adapted','technical','medium',7,'general'),
('Applies','Applied','technical','medium',7,'general'),
('Determines','Determined','technical','medium',7,'general'),
('Compiles','Compiled','technical','medium',7,'general'),
('Extracts','Extracted','technical','medium',7,'general'),
('Plots','Plotted','technical','medium',7,'general'),
('Produces','Produced','technical','high',8,'general'),
('Specifies','Specified','technical','medium',7,'general'),
('Studies','Studied','technical','medium',7,'general'),
('Synthesizes','Synthesized','technical','high',8,'general'),
('Translates','Translated','technical','medium',7,'general'),
('Debugs','Debugged','technical','high',8,'general'),
('Programs','Programmed','technical','high',8,'general'),
('Migrates','Migrated','technical','high',8,'general'),
('Scales','Scaled','technical','high',8,'general'),
('Rebuilds','Rebuilt','technical','high',8,'general'),
('Patches','Patched','technical','medium',7,'general'),

-- ============================================
-- TECHNICAL — IRRIGATION/AGRI SPECIFIC (40 verbs)
-- ============================================
('Irrigates','Irrigated','technical','medium',8,'irrigation'),
('Surveys','Surveyed','technical','high',8,'irrigation'),
('Maps','Mapped','technical','high',8,'irrigation'),
('Drills','Drilled','technical','high',8,'irrigation'),
('Pipes','Piped','technical','medium',7,'irrigation'),
('Channels','Channeled','technical','medium',7,'irrigation'),
('Drains','Drained','technical','medium',7,'irrigation'),
('Pumps','Pumped','technical','medium',7,'irrigation'),
('Filters','Filtered','technical','medium',7,'irrigation'),
('Harvests','Harvested','technical','medium',7,'irrigation'),
('Cultivates','Cultivated','technical','medium',7,'irrigation'),
('Monitors','Monitored','technical','medium',8,'irrigation'),
('Samples','Sampled','technical','medium',7,'irrigation'),
('Measures','Measured','technical','medium',8,'irrigation'),
('Gauges','Gauged','technical','medium',7,'irrigation'),
('Excavates','Excavated','technical','high',7,'irrigation'),
('Conserves','Conserved','technical','medium',8,'irrigation'),
('Reclaims','Reclaimed','technical','medium',7,'irrigation'),
('Extrapolates','Extrapolated','technical','medium',7,'irrigation'),
('Rotates','Rotated','technical','medium',7,'irrigation'),
('Supplements','Supplemented','technical','medium',7,'irrigation'),
('Diversifies','Diversified','technical','medium',7,'irrigation'),
('Intercepts','Intercepted','technical','medium',7,'irrigation'),
('Recharges','Recharged','technical','medium',7,'irrigation'),
('Harvests','Harvested','technical','medium',7,'irrigation'),
('Mulches','Mulched','technical','medium',7,'irrigation'),
('Terrace','Terraced','technical','medium',7,'irrigation'),
('Contours','Contoured','technical','medium',7,'irrigation'),
('Fertilizes','Fertilized','technical','medium',7,'irrigation'),
('Treats','Treated','technical','medium',7,'irrigation'),
('Chlorinates','Chlorinated','technical','medium',7,'irrigation'),
('Pressurizes','Pressurized','technical','medium',7,'irrigation'),
('Flushes','Flushed','technical','medium',7,'irrigation'),
('Backwashes','Backwashed','technical','medium',7,'irrigation'),
('Emits','Emitted','technical','medium',7,'irrigation'),
('Distributes','Distributed','technical','medium',8,'irrigation'),
('Conveys','Conveyed','technical','medium',7,'irrigation'),
('Impounds','Impounded','technical','medium',7,'irrigation'),
('Abstracts','Abstracted','technical','medium',7,'irrigation'),
('Reticulates','Reticulated','technical','medium',7,'irrigation'),

-- ============================================
-- MANAGEMENT (60 verbs)
-- ============================================
('Leads','Led','management','high',9,'general'),
('Manages','Managed','management','high',9,'general'),
('Directs','Directed','management','high',9,'general'),
('Oversees','Oversaw','management','high',8,'general'),
('Heads','Headed','management','high',8,'general'),
('Drives','Drove','management','high',8,'general'),
('Steers','Steered','management','high',8,'general'),
('Guides','Guided','management','high',8,'general'),
('Owns','Owned','management','high',8,'general'),
('Runs','Ran','management','high',8,'general'),
('Mobilizes','Mobilized','management','high',8,'general'),
('Coordinates','Coordinated','management','medium',8,'general'),
('Organizes','Organized','management','medium',8,'general'),
('Plans','Planned','management','medium',8,'general'),
('Schedules','Scheduled','management','medium',7,'general'),
('Prioritizes','Prioritized','management','medium',8,'general'),
('Allocates','Allocated','management','medium',8,'general'),
('Delegates','Delegated','management','medium',7,'general'),
('Supervises','Supervised','management','high',8,'general'),
('Mentors','Mentored','management','medium',8,'general'),
('Coaches','Coached','management','medium',8,'general'),
('Recruits','Recruited','management','medium',7,'general'),
('Onboards','Onboarded','management','medium',7,'general'),
('Restructures','Restructured','management','high',8,'general'),
('Streamlines','Streamlined','management','high',8,'general'),
('Launches','Launched','management','high',8,'general'),
('Establishes','Established','management','high',8,'general'),
('Administers','Administered','management','medium',7,'general'),
('Assigns','Assigned','management','medium',7,'general'),
('Authorizes','Authorized','management','medium',7,'general'),
('Chairs','Chaired','management','high',8,'general'),
('Consolidates','Consolidated','management','high',8,'general'),
('Controls','Controlled','management','medium',7,'general'),
('Decides','Decided','management','high',8,'general'),
('Executes','Executed','management','high',8,'general'),
('Founds','Founded','management','high',9,'general'),
('Handles','Handled','management','medium',7,'general'),
('Initiates','Initiated','management','high',8,'general'),
('Introduces','Introduced','management','high',8,'general'),
('Motivates','Motivated','management','high',8,'general'),
('Appoints','Appointed','management','medium',7,'general'),
('Approves','Approved','management','medium',7,'general'),
('Centralizes','Centralized','management','medium',7,'general'),
('Enforces','Enforced','management','medium',7,'general'),
('Evaluates','Evaluated','management','high',8,'general'),
('Expands','Expanded','management','high',8,'general'),
('Governs','Governed','management','high',8,'general'),
('Implements','Implemented','management','high',9,'general'),
('Improves','Improved','management','high',8,'general'),
('Increases','Increased','management','high',8,'general'),
('Modernizes','Modernized','management','high',8,'general'),
('Revitalizes','Revitalized','management','high',8,'general'),
('Transforms','Transformed','management','high',9,'general'),
('Unifies','Unified','management','high',8,'general'),
('Upgrades','Upgraded','management','high',8,'general'),
('Catalyzes','Catalyzed','management','high',8,'general'),
('Accelerates','Accelerated','management','high',8,'general'),
('Empowers','Empowered','management','high',8,'general'),
('Inspires','Inspired','management','high',8,'general'),
('Positions','Positioned','management','high',8,'general'),

-- ============================================
-- ANALYSIS (60 verbs)
-- ============================================
('Analyzes','Analyzed','analysis','high',9,'general'),
('Assesses','Assessed','analysis','high',9,'general'),
('Evaluates','Evaluated','analysis','high',8,'general'),
('Investigates','Investigated','analysis','high',8,'general'),
('Examines','Examined','analysis','high',8,'general'),
('Benchmarks','Benchmarked','analysis','high',8,'general'),
('Audits','Audited','analysis','high',8,'general'),
('Reviews','Reviewed','analysis','medium',8,'general'),
('Identifies','Identified','analysis','medium',8,'general'),
('Tracks','Tracked','analysis','medium',8,'general'),
('Reports','Reported','analysis','medium',8,'general'),
('Models','Modeled','analysis','high',8,'general'),
('Forecasts','Forecasted','analysis','high',8,'general'),
('Projects','Projected','analysis','medium',8,'general'),
('Interprets','Interpreted','analysis','medium',8,'general'),
('Processes','Processed','analysis','medium',7,'general'),
('Reconciles','Reconciled','analysis','medium',7,'general'),
('Quantifies','Quantified','analysis','high',8,'general'),
('Calculates','Calculated','analysis','medium',8,'general'),
('Simulates','Simulated','analysis','high',8,'general'),
('Clarifies','Clarified','analysis','medium',7,'general'),
('Collects','Collected','analysis','medium',8,'general'),
('Critiques','Critiqued','analysis','high',7,'general'),
('Detects','Detected','analysis','medium',8,'general'),
('Determines','Determined','analysis','medium',8,'general'),
('Experiments','Experimented','analysis','medium',7,'general'),
('Explores','Explored','analysis','medium',7,'general'),
('Formulates','Formulated','analysis','high',8,'general'),
('Gathers','Gathered','analysis','medium',8,'general'),
('Locates','Located','analysis','medium',7,'general'),
('Organizes','Organized','analysis','medium',8,'general'),
('Summarizes','Summarized','analysis','medium',8,'general'),
('Systematizes','Systematized','analysis','medium',7,'general'),
('Searches','Searched','analysis','medium',7,'general'),
('Compares','Compared','analysis','medium',7,'general'),
('Conducts','Conducted','analysis','medium',8,'general'),
('Discovers','Discovered','analysis','high',8,'general'),
('Uncovers','Uncovered','analysis','high',8,'general'),
('Prioritizes','Prioritized','analysis','medium',8,'general'),
('Positions','Positioned','analysis','medium',7,'general'),
('Researches','Researched','analysis','high',8,'general'),
('Validates','Validated','analysis','medium',8,'general'),
('Tests','Tested','analysis','medium',8,'general'),
('Appraises','Appraised','analysis','high',8,'general'),
('Classifies','Classified','analysis','medium',7,'general'),
('Categorizes','Categorized','analysis','medium',7,'general'),
('Correlates','Correlated','analysis','high',8,'general'),
('Extrapolates','Extrapolated','analysis','high',7,'general'),
('Interpolates','Interpolated','analysis','high',7,'general'),
('Pinpoints','Pinpointed','analysis','high',8,'general'),
('Profiles','Profiled','analysis','medium',7,'general'),
('Screens','Screened','analysis','medium',7,'general'),
('Segments','Segmented','analysis','medium',7,'general'),
('Triangulates','Triangulated','analysis','high',7,'general'),
('Weighs','Weighed','analysis','medium',7,'general'),
('Maps','Mapped','analysis','high',8,'general'),
('Diagnoses','Diagnosed','analysis','high',8,'general'),
('Monitors','Monitored','analysis','medium',8,'general'),
('Measures','Measured','analysis','medium',8,'general'),
('Scans','Scanned','analysis','medium',7,'general'),

-- ============================================
-- COMMUNICATION (60 verbs)
-- ============================================
('Presents','Presented','communication','high',8,'general'),
('Advises','Advised','communication','high',8,'general'),
('Pitches','Pitched','communication','high',8,'general'),
('Negotiates','Negotiated','communication','high',8,'general'),
('Influences','Influenced','communication','high',8,'general'),
('Persuades','Persuaded','communication','high',8,'general'),
('Advocates','Advocated','communication','high',8,'general'),
('Trains','Trained','communication','medium',8,'general'),
('Educates','Educated','communication','medium',8,'general'),
('Briefs','Briefed','communication','medium',8,'general'),
('Updates','Updated','communication','medium',7,'general'),
('Communicates','Communicated','communication','medium',7,'general'),
('Engages','Engaged','communication','medium',8,'general'),
('Consults','Consulted','communication','medium',8,'general'),
('Collaborates','Collaborated','communication','medium',8,'general'),
('Partners','Partnered','communication','medium',7,'general'),
('Addresses','Addressed','communication','medium',8,'general'),
('Arbitrates','Arbitrated','communication','high',7,'general'),
('Arranges','Arranged','communication','medium',7,'general'),
('Authors','Authored','communication','medium',7,'general'),
('Corresponds','Corresponded','communication','medium',7,'general'),
('Develops','Developed','communication','medium',8,'general'),
('Drafts','Drafted','communication','medium',8,'general'),
('Enlists','Enlisted','communication','medium',7,'general'),
('Interprets','Interpreted','communication','medium',7,'general'),
('Lectures','Lectured','communication','medium',7,'general'),
('Mediates','Mediated','communication','high',8,'general'),
('Moderates','Moderated','communication','medium',7,'general'),
('Promotes','Promoted','communication','high',8,'general'),
('Proposes','Proposed','communication','high',8,'general'),
('Publicizes','Publicized','communication','high',7,'general'),
('Recruits','Recruited','communication','medium',7,'general'),
('Speaks','Spoke','communication','medium',7,'general'),
('Translates','Translated','communication','medium',7,'general'),
('Writes','Wrote','communication','medium',8,'general'),
('Clarifies','Clarified','communication','medium',7,'general'),
('Conveys','Conveyed','communication','medium',7,'general'),
('Convinces','Convinced','communication','high',8,'general'),
('Counsels','Counseled','communication','medium',7,'general'),
('Demonstrates','Demonstrated','communication','medium',8,'general'),
('Describes','Described','communication','medium',7,'general'),
('Discusses','Discussed','communication','medium',7,'general'),
('Encourages','Encouraged','communication','medium',7,'general'),
('Explains','Explained','communication','medium',7,'general'),
('Informs','Informed','communication','medium',7,'general'),
('Instructs','Instructed','communication','medium',7,'general'),
('Lobbies','Lobbied','communication','high',7,'general'),
('Observes','Observed','communication','medium',7,'general'),
('Outlines','Outlined','communication','medium',7,'general'),
('Participates','Participated','communication','low',7,'general'),
('Responds','Responded','communication','medium',7,'general'),
('Resolves','Resolved','communication','high',8,'general'),
('Stimulates','Stimulated','communication','high',7,'general'),
('Suggests','Suggested','communication','medium',7,'general'),
('Synthesizes','Synthesized','communication','high',8,'general'),
('Disseminates','Disseminated','communication','medium',8,'government'),
('Coordinates','Coordinated','communication','medium',8,'general'),
('Liaises','Liaised','communication','low',7,'general'),
('Supports','Supported','communication','low',7,'general'),
('Networks','Networked','communication','medium',7,'general'),

-- ============================================
-- FINANCIAL (40 verbs)
-- ============================================
('Generates','Generated','financial','high',9,'general'),
('Grows','Grew','financial','high',9,'general'),
('Increases','Increased','financial','high',8,'general'),
('Cuts','Cut','financial','high',8,'general'),
('Reduces','Reduced','financial','high',8,'general'),
('Saves','Saved','financial','high',8,'general'),
('Recovers','Recovered','financial','high',8,'general'),
('Maximizes','Maximized','financial','high',8,'general'),
('Budgets','Budgeted','financial','medium',7,'general'),
('Forecasts','Forecasted','financial','high',8,'general'),
('Secures','Secured','financial','high',8,'general'),
('Closes','Closed','financial','high',8,'general'),
('Delivers','Delivered','financial','high',8,'general'),
('Audits','Audited','financial','high',8,'general'),
('Reconciles','Reconciled','financial','medium',7,'general'),
('Projects','Projected','financial','medium',8,'general'),
('Allocates','Allocated','financial','medium',8,'general'),
('Invests','Invested','financial','high',8,'general'),
('Acquires','Acquired','financial','high',8,'general'),
('Monetizes','Monetized','financial','high',8,'general'),
('Diversifies','Diversified','financial','high',8,'general'),
('Finances','Financed','financial','high',8,'general'),
('Procures','Procured','financial','medium',7,'general'),
('Administers','Administered','financial','medium',7,'general'),
('Appraises','Appraised','financial','high',8,'general'),
('Balances','Balanced','financial','medium',7,'general'),
('Calculates','Calculated','financial','medium',8,'general'),
('Accounts','Accounted','financial','medium',7,'general'),
('Controls','Controlled','financial','medium',7,'general'),
('Exceeds','Exceeded','financial','high',8,'general'),
('Boosts','Boosted','financial','high',8,'general'),
('Accelerates','Accelerated','financial','high',8,'general'),
('Captures','Captured','financial','high',8,'general'),
('Expands','Expanded','financial','high',8,'general'),
('Liquidates','Liquidated','financial','medium',7,'general'),
('Optimizes','Optimized','financial','high',8,'general'),
('Retains','Retained','financial','medium',8,'general'),
('Converts','Converted','financial','medium',7,'general'),
('Targets','Targeted','financial','medium',7,'general'),
('Negotiates','Negotiated','financial','high',8,'general'),

-- ============================================
-- NGO/GOVERNMENT/DEVELOPMENT (50 verbs)
-- ============================================
('Coordinates','Coordinated','ngo','medium',8,'government'),
('Facilitates','Facilitated','ngo','medium',8,'government'),
('Mobilizes','Mobilized','ngo','high',8,'government'),
('Disseminates','Disseminated','ngo','medium',8,'government'),
('Monitors','Monitored','ngo','medium',8,'government'),
('Evaluates','Evaluated','ngo','high',8,'government'),
('Implements','Implemented','ngo','high',9,'government'),
('Develops','Developed','ngo','high',9,'government'),
('Supports','Supported','ngo','low',7,'government'),
('Strengthens','Strengthened','ngo','medium',8,'government'),
('Builds','Built','ngo','high',8,'government'),
('Engages','Engaged','ngo','medium',8,'government'),
('Advocates','Advocated','ngo','high',8,'government'),
('Sensitizes','Sensitized','ngo','medium',7,'government'),
('Trains','Trained','ngo','medium',8,'government'),
('Empowers','Empowered','ngo','high',8,'government'),
('Reaches','Reached','ngo','medium',8,'government'),
('Serves','Served','ngo','medium',8,'government'),
('Responds','Responded','ngo','medium',8,'government'),
('Assesses','Assessed','ngo','high',9,'government'),
('Prepares','Prepared','ngo','medium',8,'government'),
('Collects','Collected','ngo','medium',8,'government'),
('Reports','Reported','ngo','medium',8,'government'),
('Conducts','Conducted','ngo','medium',8,'government'),
('Reviews','Reviewed','ngo','medium',8,'government'),
('Documents','Documented','ngo','medium',8,'government'),
('Submits','Submitted','ngo','medium',7,'government'),
('Liaises','Liaised','ngo','low',7,'government'),
('Represents','Represented','ngo','medium',7,'government'),
('Advises','Advised','ngo','high',8,'government'),
('Recommends','Recommended','ngo','high',8,'government'),
('Formulates','Formulated','ngo','high',8,'government'),
('Drafts','Drafted','ngo','medium',8,'government'),
('Establishes','Established','ngo','high',8,'government'),
('Launches','Launched','ngo','high',8,'government'),
('Pilots','Piloted','ngo','high',8,'government'),
('Scales','Scaled','ngo','high',8,'government'),
('Sustains','Sustained','ngo','medium',7,'government'),
('Integrates','Integrated','ngo','high',8,'government'),
('Networks','Networked','ngo','medium',7,'government'),
('Organizes','Organized','ngo','medium',8,'government'),
('Reinforces','Reinforced','ngo','medium',7,'government'),
('Mediates','Mediated','ngo','high',8,'government'),
('Arbitrates','Arbitrated','ngo','high',7,'government'),
('Ensures','Ensured','ngo','medium',7,'government'),
('Oversees','Oversaw','ngo','high',8,'government'),
('Manages','Managed','ngo','high',9,'government'),
('Leads','Led','ngo','high',9,'government'),
('Chairs','Chaired','ngo','high',8,'government'),
('Steers','Steered','ngo','high',8,'government'),

-- ============================================
-- HEALTHCARE/SCIENCE/RESEARCH (40 verbs)
-- ============================================
('Diagnoses','Diagnosed','healthcare','high',8,'healthcare'),
('Treats','Treated','healthcare','high',8,'healthcare'),
('Monitors','Monitored','healthcare','medium',8,'healthcare'),
('Prescribes','Prescribed','healthcare','high',8,'healthcare'),
('Administers','Administered','healthcare','medium',8,'healthcare'),
('Rehabilitates','Rehabilitated','healthcare','medium',8,'healthcare'),
('Prevents','Prevented','healthcare','high',8,'healthcare'),
('Improves','Improved','healthcare','high',8,'healthcare'),
('Enhances','Enhanced','healthcare','high',8,'healthcare'),
('Reduces','Reduced','healthcare','high',8,'healthcare'),
('Screens','Screened','healthcare','medium',8,'healthcare'),
('Evaluates','Evaluated','healthcare','high',8,'healthcare'),
('Assesses','Assessed','healthcare','high',8,'healthcare'),
('Examines','Examined','healthcare','high',8,'healthcare'),
('Researches','Researched','healthcare','high',8,'healthcare'),
('Experiments','Experimented','healthcare','medium',7,'healthcare'),
('Investigates','Investigated','healthcare','high',8,'healthcare'),
('Publishes','Published','healthcare','high',7,'healthcare'),
('Collaborates','Collaborated','healthcare','medium',8,'healthcare'),
('Documents','Documented','healthcare','medium',8,'healthcare'),
('Collects','Collected','healthcare','medium',8,'healthcare'),
('Analyzes','Analyzed','healthcare','high',9,'healthcare'),
('Interprets','Interpreted','healthcare','medium',8,'healthcare'),
('Reports','Reported','healthcare','medium',8,'healthcare'),
('Validates','Validated','healthcare','medium',8,'healthcare'),
('Synthesizes','Synthesized','healthcare','high',8,'healthcare'),
('Reviews','Reviewed','healthcare','medium',8,'healthcare'),
('Counsels','Counseled','healthcare','medium',7,'healthcare'),
('Educates','Educated','healthcare','medium',8,'healthcare'),
('Trains','Trained','healthcare','medium',8,'healthcare'),
('Identifies','Identified','healthcare','medium',8,'healthcare'),
('Tests','Tested','healthcare','medium',8,'healthcare'),
('Measures','Measured','healthcare','medium',8,'healthcare'),
('Calculates','Calculated','healthcare','medium',8,'healthcare'),
('Formulates','Formulated','healthcare','high',8,'healthcare'),
('Designs','Designed','healthcare','high',8,'healthcare'),
('Implements','Implemented','healthcare','high',9,'healthcare'),
('Develops','Developed','healthcare','high',9,'healthcare'),
('Coordinates','Coordinated','healthcare','medium',8,'healthcare'),
('Improves','Improved','healthcare','high',8,'healthcare'),

-- ============================================
-- EDUCATION/TRAINING (30 verbs)
-- ============================================
('Teaches','Taught','education','medium',8,'education'),
('Trains','Trained','education','medium',8,'education'),
('Educates','Educated','education','medium',8,'education'),
('Mentors','Mentored','education','medium',8,'education'),
('Coaches','Coached','education','medium',8,'education'),
('Guides','Guided','education','high',8,'education'),
('Facilitates','Facilitated','education','medium',8,'education'),
('Develops','Developed','education','high',9,'education'),
('Designs','Designed','education','high',8,'education'),
('Creates','Created','education','high',8,'education'),
('Evaluates','Evaluated','education','high',8,'education'),
('Assesses','Assessed','education','high',8,'education'),
('Adapts','Adapted','education','medium',7,'education'),
('Delivers','Delivered','education','high',8,'education'),
('Implements','Implemented','education','high',9,'education'),
('Instructs','Instructed','education','medium',8,'education'),
('Lectures','Lectured','education','medium',7,'education'),
('Demonstrates','Demonstrated','education','medium',8,'education'),
('Explains','Explained','education','medium',7,'education'),
('Encourages','Encouraged','education','medium',7,'education'),
('Motivates','Motivated','education','high',8,'education'),
('Inspires','Inspired','education','high',8,'education'),
('Supports','Supported','education','low',7,'education'),
('Assists','Assisted','education','low',7,'education'),
('Coordinates','Coordinated','education','medium',8,'education'),
('Manages','Managed','education','high',8,'education'),
('Leads','Led','education','high',9,'education'),
('Initiates','Initiated','education','high',8,'education'),
('Establishes','Established','education','high',8,'education'),
('Transforms','Transformed','education','high',9,'education'),

-- ============================================
-- TECH/SOFTWARE (40 verbs)
-- ============================================
('Codes','Coded','tech','high',9,'tech'),
('Programs','Programmed','tech','high',9,'tech'),
('Develops','Developed','tech','high',9,'tech'),
('Builds','Built','tech','high',9,'tech'),
('Deploys','Deployed','tech','high',9,'tech'),
('Ships','Shipped','tech','high',9,'tech'),
('Debugs','Debugged','tech','high',8,'tech'),
('Refactors','Refactored','tech','high',8,'tech'),
('Architects','Architected','tech','high',9,'tech'),
('Designs','Designed','tech','high',9,'tech'),
('Optimizes','Optimized','tech','high',8,'tech'),
('Integrates','Integrated','tech','high',8,'tech'),
('Automates','Automated','tech','high',8,'tech'),
('Migrates','Migrated','tech','high',8,'tech'),
('Configures','Configured','tech','medium',8,'tech'),
('Tests','Tested','tech','medium',8,'tech'),
('Reviews','Reviewed','tech','medium',8,'tech'),
('Documents','Documented','tech','medium',7,'tech'),
('Implements','Implemented','tech','high',9,'tech'),
('Scales','Scaled','tech','high',8,'tech'),
('Secures','Secured','tech','high',8,'tech'),
('Monitors','Monitored','tech','medium',8,'tech'),
('Maintains','Maintained','tech','medium',7,'tech'),
('Analyzes','Analyzed','tech','high',9,'tech'),
('Profiles','Profiled','tech','medium',7,'tech'),
('Patches','Patched','tech','medium',7,'tech'),
('Containerizes','Containerized','tech','high',8,'tech'),
('Orchestrates','Orchestrated','tech','high',8,'tech'),
('Provisions','Provisioned','tech','medium',7,'tech'),
('Pipelines','Pipelined','tech','high',8,'tech'),
('Bootstraps','Bootstrapped','tech','high',8,'tech'),
('Scaffolds','Scaffolded','tech','medium',7,'tech'),
('Lints','Linted','tech','medium',7,'tech'),
('Benchmarks','Benchmarked','tech','medium',8,'tech'),
('Validates','Validated','tech','medium',8,'tech'),
('Indexes','Indexed','tech','medium',7,'tech'),
('Caches','Cached','tech','medium',7,'tech'),
('Syncs','Synced','tech','medium',7,'tech'),
('Parses','Parsed','tech','medium',7,'tech'),
('Renders','Rendered','tech','medium',7,'tech'),

-- ============================================
-- SALES/COMMERCIAL (30 verbs)
-- ============================================
('Sells','Sold','sales','high',9,'sales'),
('Closes','Closed','sales','high',9,'sales'),
('Pitches','Pitched','sales','high',8,'sales'),
('Generates','Generated','sales','high',9,'sales'),
('Grows','Grew','sales','high',9,'sales'),
('Retains','Retained','sales','high',8,'sales'),
('Upsells','Upsold','sales','high',8,'sales'),
('Cross-sells','Cross-sold','sales','high',8,'sales'),
('Acquires','Acquired','sales','high',8,'sales'),
('Converts','Converted','sales','high',8,'sales'),
('Develops','Developed','sales','high',9,'sales'),
('Manages','Managed','sales','high',9,'sales'),
('Builds','Built','sales','high',8,'sales'),
('Expands','Expanded','sales','high',8,'sales'),
('Identifies','Identified','sales','medium',8,'sales'),
('Prospects','Prospected','sales','high',8,'sales'),
('Qualifies','Qualified','sales','medium',7,'sales'),
('Negotiates','Negotiated','sales','high',8,'sales'),
('Presents','Presented','sales','high',8,'sales'),
('Demonstrates','Demonstrated','sales','medium',8,'sales'),
('Advises','Advised','sales','high',8,'sales'),
('Engages','Engaged','sales','medium',8,'sales'),
('Nurtures','Nurtured','sales','medium',7,'sales'),
('Follows','Followed','sales','medium',7,'sales'),
('Responds','Responded','sales','medium',7,'sales'),
('Satisfies','Satisfied','sales','medium',7,'sales'),
('Delights','Delighted','sales','high',8,'sales'),
('Exceeds','Exceeded','sales','high',8,'sales'),
('Hits','Hit','sales','high',8,'sales'),
('Surpasses','Surpassed','sales','high',8,'sales');

-- ─── block 2/6 ────────────────────────────────
-- ============================================
-- GENERAL BULLET STRUCTURES
-- ============================================
INSERT OR IGNORE INTO cv_sentence_structures
(pattern_label, pattern, word_count_min, word_count_max, example, use_frequency, section) VALUES

-- SHORT (8-12 words)
('short','VERB + OBJECT + LOCATION',8,12,'Mapped irrigation needs across 8 farms in Central Kenya.','common','bullet'),
('short','VERB + NUMBER + OBJECT',8,12,'Managed 8 enterprise accounts across two regions.','common','bullet'),
('short','VERB + OBJECT + TIMEFRAME',8,12,'Delivered 3 irrigation projects within a 6-week window.','common','bullet'),
('short','VERB + OBJECT — RESULT',8,12,'Cut water waste by roughly 14% — farms noticed immediately.','occasional','bullet'),
('short','SOLE OWNERSHIP',5,10,'Sole field engineer on the Kiambu drip project.','rare','bullet'),
('short','VERB + OBJECT + FOR WHO',8,12,'Trained 12 farm operators on drip system maintenance.','common','bullet'),
('short','VERB + METRIC + OBJECT',8,12,'Reduced water waste by ~14% across all project sites.','common','bullet'),
('short','VERB + OBJECT FAST',5,9,'Built the irrigation layout in 4 days.','occasional','bullet'),
('short','PURE FACT',6,10,'Zero missed deadlines across 8 consecutive projects.','rare','bullet'),
('short','VERB + TOOL + OBJECT',8,12,'Used AutoCAD to design layouts for 6 client farms.','common','bullet'),

-- MEDIUM (13-20 words)
('medium','VERB + OBJECT + CONTEXT + RESULT',13,20,'Designed drip systems for smallholder farms, cutting water usage by roughly 14%.','common','bullet'),
('medium','VERB + OBJECT + FOR WHO + RESULT',13,20,'Built irrigation layouts for 6 NGO partner farms, reducing water costs significantly.','common','bullet'),
('medium','VERB + OBJECT + USING TOOL + RESULT',13,20,'Analyzed catchment data using GIS, identifying 3 high-risk drought zones.','common','bullet'),
('medium','VERB + OBJECT + OVER TIMEFRAME + RESULT',13,20,'Monitored soil moisture across 12 sites over 6 months, flagging 2 critical failures early.','occasional','bullet'),
('medium','CONTEXT + VERB + OBJECT + RESULT',13,20,'Working across 3 counties, coordinated drought response plans for 8 community groups.','occasional','bullet'),
('medium','VERB + OBJECT + DESPITE CONDITION',13,20,'Delivered all 4 systems on schedule despite supply chain delays during peak season.','occasional','bullet'),
('medium','VERB + OBJECT + WITH TEAM + RESULT',13,20,'Led a 5-person team to commission 3 drip systems, finishing 2 weeks ahead of schedule.','common','bullet'),
('medium','VERB + PROCESS + RESULT + METRIC',13,20,'Streamlined site survey process, reducing assessment time from 3 days to roughly 1 day.','common','bullet'),
('medium','VERB + OBJECT + SCOPE + RESULT',13,20,'Managed 8 client accounts across Central Kenya, generating KES 800K in annual revenue.','common','bullet'),
('medium','VERB + OBJECT + STANDARD + RESULT',13,20,'Implemented quality control checks for grain storage, cutting spoilage by roughly 20%.','common','bullet'),

-- LONG (21-30 words)
('long','OPENER + VERB + OBJECT + CONTEXT + RESULT + IMPACT',21,30,'During peak drought season, coordinated early warning data collection across 5 sub-counties — zero delayed bulletins across all reporting periods.','occasional','bullet'),
('long','VERB + OBJECT + CONTEXT + RESULT + STAKEHOLDER IMPACT',21,30,'Designed and implemented a drip irrigation system for a 40-hectare farm in Kiambu, cutting water usage by roughly 28% and improving yield consistency for 3 seasons.','occasional','bullet'),
('long','SITUATION + VERB + OBJECT + RESULT + BROADER IMPACT',21,30,'With limited field resources, built a soil moisture monitoring process from scratch — now used across all 6 project sites without modification.','rare','bullet'),
('long','VERB + COMPLEX OBJECT + HOW + RESULT + WHO BENEFITED',21,30,'Coordinated food security vulnerability assessments for 12 NGO partner communities using GIS mapping, providing data that informed county-level drought response planning.','occasional','bullet'),
('long','VERB + OBJECT + OVER TIME + RESULT + SCALE',21,30,'Monitored water usage patterns across 8 enterprise farms over 9 months, identifying efficiency gaps that reduced overall consumption by roughly 18%.','occasional','bullet'),

-- PERSONALITY (em-dash style)
('personality','SITUATION — HOW YOU HANDLED IT',10,20,'First contact for client escalations on site — resolved 4 pump failures without escalating to management.','rare','bullet'),
('personality','UNEXPECTED RESPONSIBILITY — OUTCOME',10,20,'Inherited a failing drip system midway through installation — got it running 3 days ahead of the revised deadline.','rare','bullet'),
('personality','SOLO OWNERSHIP — RESULT',8,15,'Sole engineer on the v2 system redesign — shipped on time with zero rework.','rare','bullet'),
('personality','CHALLENGE — HOW SOLVED — RESULT',12,20,'System failed 2 hours before client inspection — diagnosed and fixed the blockage alone, inspection passed.','rare','bullet'),
('personality','RECOGNITION — WHAT EARNED IT',8,15,'Clients specifically requested me for repeat installations — happened 5 times in 18 months.','rare','bullet'),

-- ============================================
-- FIELD-SPECIFIC: IRRIGATION/AGRI
-- ============================================
('short','VERB + IRRIGATION OBJECT + LOCATION',8,12,'Installed drip systems across 6 farms in Kiambu County.','common','bullet'),
('short','VERB + WATER METRIC + CONTEXT',8,12,'Cut water usage by ~18% across all drip installations.','common','bullet'),
('medium','VERB + SYSTEM TYPE + FOR SCALE + RESULT',13,20,'Designed center pivot irrigation for 40-hectare maize farm, improving water distribution uniformity significantly.','common','bullet'),
('medium','VERB + SOIL ANALYSIS + HOW + RESULT',13,20,'Conducted soil moisture analysis for 8 crop varieties, optimizing irrigation schedules and cutting waste by ~12%.','common','bullet'),
('medium','VERB + SITE SURVEY + SCOPE + OUTPUT',13,20,'Surveyed 6 client sites across Central Kenya, producing irrigation system designs tailored to each soil type.','common','bullet'),
('medium','VERB + MAINTENANCE + SCOPE + RESULT',13,20,'Maintained irrigation infrastructure for 8 enterprise clients, keeping system uptime above 97% across all sites.','common','bullet'),
('long','VERB + FULL SYSTEM + FOR WHO + HOW + RESULT + IMPACT',21,30,'Designed and commissioned a drip irrigation system for a 15-hectare tomato farm in Machakos, applying GIS soil mapping to optimize emitter placement — yield improved by roughly 30% in first season.','occasional','bullet'),

-- ============================================
-- FIELD-SPECIFIC: DROUGHT MANAGEMENT/NGO
-- ============================================
('short','VERB + DROUGHT OBJECT + LOCATION',8,12,'Collected early warning data across 5 sub-counties in Turkana.','common','bullet'),
('short','VERB + REPORT TYPE + FREQUENCY',8,12,'Prepared monthly drought bulletins for county stakeholders.','common','bullet'),
('medium','VERB + ASSESSMENT TYPE + SCOPE + OUTPUT',13,20,'Conducted food security vulnerability assessments for 12 communities, producing data used in county drought response planning.','common','bullet'),
('medium','VERB + RESPONSE PLAN + WITH WHO + RESULT',13,20,'Developed contingency plans with county government and NGO partners, reducing drought response activation time significantly.','common','bullet'),
('medium','VERB + GIS TOOL + FOR WHAT + RESULT',13,20,'Used GIS and remote sensing to map drought-affected zones, prioritizing 3 sub-counties for immediate intervention.','common','bullet'),
('medium','VERB + STAKEHOLDERS + HOW + OUTCOME',13,20,'Coordinated 8 government and NGO stakeholders during drought response, ensuring aligned messaging and zero duplication of effort.','common','bullet'),
('long','VERB + PROGRAM + SCOPE + METHOD + RESULT + BENEFICIARIES',21,30,'Implemented a drought resilience program across 6 sub-counties using participatory community mapping — reached 2,400 farming households and improved early warning response times by roughly 35%.','occasional','bullet'),

-- ============================================
-- FIELD-SPECIFIC: GOVERNMENT/PUBLIC SERVICE
-- ============================================
('short','VERB + POLICY OBJECT + SCOPE',8,12,'Implemented county drought response policy across 4 sub-counties.','common','bullet'),
('short','VERB + PROGRAM + FOR WHO',8,12,'Coordinated food security programs for 1,200 vulnerable households.','common','bullet'),
('medium','VERB + REGULATORY TASK + HOW + RESULT',13,20,'Monitored compliance with water use regulations across 8 irrigation schemes, flagging 2 violations for corrective action.','common','bullet'),
('medium','VERB + STAKEHOLDER MEETING + SCOPE + OUTCOME',13,20,'Facilitated quarterly stakeholder forums with county officials and NGO partners, resulting in coordinated drought response plans.','common','bullet'),
('long','VERB + PROGRAM + INTERAGENCY + HOW + RESULT + SCALE',21,30,'Led interagency drought response coordination across 3 counties, working with 12 government and development partners to deploy emergency relief — reached 8,000 households within 2 weeks of activation.','occasional','bullet'),

-- ============================================
-- FIELD-SPECIFIC: TECH/SOFTWARE
-- ============================================
('short','VERB + TECH OBJECT + METRIC',8,12,'Shipped 3 features that cut API response time by 40%.','common','bullet'),
('short','VERB + SYSTEM + RESULT',8,12,'Debugged legacy auth system — login failures dropped to zero.','common','bullet'),
('medium','VERB + STACK + FOR WHO + RESULT',13,20,'Built a React dashboard for county drought monitoring, reducing data reporting time from 3 days to 4 hours.','common','bullet'),
('medium','VERB + ARCHITECTURE + HOW + RESULT',13,20,'Architected a hybrid Supabase-Cloudflare D1 system, cutting infrastructure costs to near zero while maintaining 99.9% uptime.','common','bullet'),
('long','VERB + SYSTEM + TECH STACK + SCALE + RESULT + IMPACT',21,30,'Built and deployed a real-time irrigation monitoring dashboard using React, Cloudflare Workers, and D1 — processing data from 40+ sensors with sub-100ms response times across all client farms.','occasional','bullet'),

-- ============================================
-- FIELD-SPECIFIC: ECONOMICS/FINANCE
-- ============================================
('short','VERB + FINANCIAL OBJECT + METRIC',8,12,'Grew client portfolio revenue by ~22% in 9 months.','common','bullet'),
('short','VERB + DATA + FOR WHO',8,12,'Analyzed market trends for 6 irrigation product categories.','common','bullet'),
('medium','VERB + MODEL + HOW + OUTPUT',13,20,'Modeled irrigation system ROI for 8 client scenarios, producing business cases that secured KES 2M in project approvals.','common','bullet'),
('medium','VERB + COST ANALYSIS + SCOPE + RESULT',13,20,'Conducted cost-benefit analysis for 5 drip irrigation projects, identifying KES 450K in potential savings over 3 years.','common','bullet'),
('long','VERB + FINANCIAL PROGRAM + METHOD + RESULT + STAKEHOLDERS',21,30,'Developed a financial viability framework for smallholder irrigation investments, analyzing 15 farm scenarios across 3 agro-ecological zones — adopted by county agriculture office as standard assessment tool.','occasional','bullet'),

-- ============================================
-- FIELD-SPECIFIC: SALES/COMMERCIAL
-- ============================================
('short','VERB + REVENUE + TIMEFRAME',8,12,'Generated KES 800K in irrigation equipment sales in 2024.','common','bullet'),
('short','VERB + ACCOUNTS + SCOPE',8,12,'Managed 8 enterprise accounts across Nairobi and Central Kenya.','common','bullet'),
('medium','VERB + PRODUCT + FOR WHO + RESULT',13,20,'Presented drip irrigation specifications to 12 commercial farmers, converting 8 into full system installations.','common','bullet'),
('medium','VERB + RELATIONSHIP + HOW + RESULT',13,20,'Built long-term relationships with 5 key accounts, resulting in ~40% of revenue coming from repeat business.','common','bullet'),
('long','VERB + SALES PROCESS + SCOPE + METHOD + RESULT + METRIC',21,30,'Redesigned the client needs assessment process for irrigation sales, introducing site surveys and soil analysis reports — average deal size grew by roughly 35% and client satisfaction improved noticeably.','occasional','bullet'),

-- ============================================
-- SUMMARY STRUCTURES
-- ============================================
('summary_s1','WHO YOU ARE + YEARS + FIELD',8,12,'Biosystems engineer with 3 years in irrigation and drought risk management.','common','summary'),
('summary_s1_ngo','WHO YOU ARE + YEARS + SECTOR',8,12,'Development professional with 4 years coordinating food security programs across Kenya.','common','summary'),
('summary_s1_tech','WHO YOU ARE + YEARS + STACK',8,12,'Software engineer with 2 years building full-stack web applications.','common','summary'),
('summary_s1_govt','WHO YOU ARE + YEARS + ROLE',8,12,'Public sector professional with 5 years implementing county-level agricultural programs.','common','summary'),
('summary_s1_finance','WHO YOU ARE + YEARS + SPECIALIZATION',8,12,'Agricultural economist with 3 years in irrigation investment analysis and rural finance.','common','summary'),
('summary_s2','ACHIEVEMENT + METRIC + CONTEXT',15,20,'Built and managed irrigation solutions for 8 enterprise clients, generating KES 800K in annual revenue across Central Kenya.','common','summary'),
('summary_s2_ngo','PROGRAM ACHIEVEMENT + REACH',15,20,'Coordinated drought response programs reaching 2,400 farming households across 3 counties in Northern Kenya.','common','summary'),
('summary_s2_tech','TECHNICAL ACHIEVEMENT + METRIC',15,20,'Shipped production features used by 500+ users, reducing system response time by 40%.','common','summary'),
('summary_s3','WHAT YOU WANT — FORWARD LOOKING',8,12,'Looking for a role where field experience and data-driven thinking actually matter.','common','summary'),
('summary_s3_ngo','FORWARD LOOKING — IMPACT',8,12,'Looking to apply drought management skills at county level where impact is measurable.','common','summary'),
('summary_s3_govt','FORWARD LOOKING — CONTRIBUTION',8,12,'Looking to contribute field-tested irrigation expertise to a national water authority.','common','summary'),

-- ============================================
-- EDUCATION STRUCTURES
-- ============================================
('education','ONE FACTUAL LINE — GENERAL',8,15,'Completed coursework in irrigation design, water resources, and agricultural engineering.','common','education'),
('education','ONE FACTUAL LINE — DROUGHT',8,15,'Studied water resources management, agricultural economics, and environmental engineering.','common','education'),
('education','ONE FACTUAL LINE — TECH',8,15,'Completed software engineering training with focus on backend development and database systems.','common','education'),
('education','ONE FACTUAL LINE — THESIS',10,18,'Final-year project focused on drip irrigation design for smallholder farms in semi-arid Kenya.','occasional','education'),

-- ============================================
-- PROJECT STRUCTURES
-- ============================================
('project_l1','WHAT IT WAS — SHORT',5,10,'Designed and built a drip irrigation system for a smallholder farm.','common','project'),
('project_l1_tech','WHAT IT WAS — TECH',5,10,'Built a full-stack animal records management system using React and Laravel.','common','project'),
('project_l2','WHAT YOU DID — MEDIUM',12,18,'Applied GIS mapping and soil analysis to optimize water distribution across 4 zones.','common','project'),
('project_l2_tech','WHAT YOU DID — TECH',12,18,'Implemented RESTful API integration using Laravel Sanctum, enabling secure data exchange across platforms.','common','project'),
('project_l3','RESULT — SHORT',5,10,'Cut water usage by 29%, improving yield consistency significantly.','common','project'),
('project_l3_tech','RESULT — TECH',5,10,'Reduced record retrieval time by 40% through optimized database indexing.','common','project');

-- ─── block 3/6 ────────────────────────────────
INSERT OR IGNORE INTO cv_banned_phrases (phrase, replacement, severity) VALUES

-- CRITICAL — Corporate Buzzwords
('leveraging','using','critical'),
('spearheaded','led','critical'),
('utilized','used','critical'),
('synergizing','combining','critical'),
('synergy','collaboration','critical'),
('paradigm shift','major change','critical'),
('innovative solutions','practical solutions','critical'),
('thought leader','expert','critical'),
('game changer','significant improvement','critical'),
('disruptive','transformative','critical'),
('holistic approach','comprehensive approach','critical'),
('value-added','valuable','critical'),
('move the needle','make progress','critical'),
('circle back','follow up','critical'),
('bandwidth','capacity','critical'),
('deep dive','thorough analysis','critical'),
('low-hanging fruit','quick wins','critical'),
('boil the ocean','tackle everything','critical'),
('go-to-market','launch','critical'),
('drinking the kool-aid','following the approach','critical'),
('core competency','key strength','critical'),
('best of breed','top performing','critical'),
('cutting-edge','advanced','critical'),
('state-of-the-art','modern','critical'),
('world-class','high-quality','critical'),
('best-in-class','top-performing','critical'),
('next-level','improved','critical'),
('robust','strong','critical'),
('scalable solution','solution that scales','critical'),
('seamless integration','smooth integration','critical'),

-- CRITICAL — Weak Sentence Endings
('ensuring timely delivery','','critical'),
('minimizing losses','','critical'),
('providing critical data to inform','','critical'),
('adhering to industry standards','','critical'),
('applying technical knowledge and skills to meet their specific needs','','critical'),
('applying technical knowledge and skills to meet specific needs and requirements','','critical'),
('staying up-to-date with industry developments and best practices','','critical'),
('keeping current with industry developments and proven methods','','critical'),
('ensuring accurate documentation and knowledge sharing','','critical'),
('ensuring accurate documentation and documentation','','critical'),
('and documentation','','critical'),
('drive meaningful change','improve outcomes','critical'),
('driving meaningful change','improving outcomes','critical'),
('and best practices','','critical'),
('through the application of quality control principles and techniques','','critical'),
('through the application of food safety and quality management principles and techniques','','critical'),
('through the application of water conservation principles and techniques','','critical'),
('through the application of calibration and maintenance proven methods','','critical'),
('through the use of data analysis and reporting tools','','critical'),
('through the implementation of proven methods and energy-efficient technologies','','critical'),
('through effective supply chain management and logistics planning','','critical'),
('through proactive engagement and stakeholder coordination','','critical'),
('through effective inventory management and logistics planning','','critical'),

-- HIGH — Soft Skill Buzzwords
('results-driven','','high'),
('dynamic','','high'),
('proactive','','high'),
('go-getter','','high'),
('self-starter','','high'),
('team player','','high'),
('detail-oriented','','high'),
('strategic thinker','','high'),
('problem solver','','high'),
('multitasker','','high'),
('hard worker','','high'),
('fast learner','','high'),
('outside the box','creatively','high'),
('hit the ground running','start immediately','high'),
('passionate about','focused on','high'),
('passion for','focus on','high'),
('enthusiastic about','interested in','high'),
('dedicated to','committed to','high'),
('strong work ethic','','high'),
('excellent communication skills','','high'),
('strong interpersonal skills','','high'),
('proven track record','strong record','high'),
('extensive experience','experience','high'),
('seasoned professional','experienced','high'),

-- HIGH — Overused Verbs (use sparingly not ban)
('spearheaded','led','high'),
('championed','led','high'),
('evangelized','promoted','high'),
('orchestrated','coordinated','high'),
('masterminded','planned','high'),
('catapulted','grew','high'),
('skyrocketed','increased','high'),
('revolutionized','transformed','high'),
('pioneered','introduced','high'),
('spearheading','leading','high'),

-- HIGH — Weak Openers
('responsible for','','high'),
('tasked with','','high'),
('in charge of','','high'),
('duties included','','high'),
('helped with','helped','high'),
('assisted in','helped','high'),
('worked on','developed','high'),
('was involved in','contributed to','high'),
('participated in','contributed to','high'),
('took part in','contributed to','high'),
('supported the team in','','high'),
('contributed to the success of','helped deliver','high'),

-- HIGH — Filler Phrases
('it is worth noting that','','high'),
('in order to','to','high'),
('due to the fact that','because','high'),
('in the event that','if','high'),
('at this point in time','now','high'),
('on a daily basis','daily','high'),
('in a timely manner','on time','high'),
('in a cost-effective manner','cost-effectively','high'),
('as per','as','high'),
('per our conversation','as discussed','high'),
('going forward','from now on','high'),
('at the end of the day','ultimately','high'),
('the fact of the matter is','','high'),
('needless to say','','high'),
('it goes without saying','','high'),
('as a matter of fact','','high'),

-- HIGH — Overused Transition Phrases
('furthermore','','high'),
('moreover','','high'),
('in addition to the above','','high'),
('as mentioned previously','','high'),
('as stated above','','high'),
('it should be noted that','','high'),
('it is important to note that','','high'),

-- MEDIUM — Vague Results
('improved overall efficiency','','medium'),
('enhanced productivity','','medium'),
('increased team morale','','medium'),
('improved communication','','medium'),
('enhanced collaboration','','medium'),
('fostered innovation','','medium'),
('created a culture of','','medium'),
('instilled a sense of','','medium'),
('enabled stakeholders to','','medium'),
('empowered team members to','','medium'),

-- MEDIUM — ATS Red Flags
('assisted in the development of','developed','medium'),
('played a key role in','led','medium'),
('was instrumental in','led','medium'),
('helped to ensure','ensured','medium'),
('was responsible for ensuring','ensured','medium'),
('worked closely with','collaborated with','medium'),
('on a regular basis','regularly','medium'),
('in a professional manner','professionally','medium'),
('with a high level of','with','medium'),
('to the best of my ability','','medium'),
('second to none','excellent','medium'),
('above and beyond','beyond expectations','medium'),

-- MEDIUM — Wrong Field Language
('generated revenue','(NGO/govt roles only — remove)','medium'),
('closed deals','(NGO/govt roles only — remove)','medium'),
('hit sales targets','(NGO/govt roles only — remove)','medium'),
('sales pipeline','(NGO/govt roles only — remove)','medium'),
('commissioned sales','(NGO/govt roles only — remove)','medium'),

-- MEDIUM — Repetition Triggers (max 2 per CV)
('drought resilience and preparedness plans','drought resilience','medium'),
('drought risk reduction programs','drought risk programs','medium'),
('early warning systems and food security','early warning systems','medium'),
('contingency planning and drought response','contingency planning','medium'),
('data analysis and reporting','data analysis','medium'),
('irrigation systems design and implementation','irrigation design','medium'),
('water resources management','water resources','medium');

-- ─── block 4/6 ────────────────────────────────
INSERT OR IGNORE INTO cv_result_connectors (connector, type, example, human_score) VALUES

-- METRIC — Specific Numbers
('cutting X by roughly Y%','metric','cutting water waste by roughly 14%',9),
('reducing X by ~Y%','approximate','reducing costs by ~12%',9),
('improving X by Y%','metric','improving crop yield by 23%',9),
('saving roughly X hours per week','metric','saving roughly 3 hours per week',9),
('generating KES X in Y','metric','generating KES 800K in annual revenue',9),
('serving X clients across Y','metric','serving 8 clients across Central Kenya',8),
('covering X hectares across Y','metric','covering 40 hectares across 3 counties',8),
('cutting setup time by roughly X','metric','cutting setup time by roughly 2 weeks',8),
('saving the team ~X hours per sprint','metric','saving the team ~4 hours per sprint',8),
('reducing downtime from X to Y','metric','reducing downtime from 5 to 2 days',8),
('hitting X% of quarterly targets','metric','hitting 94% of quarterly targets',8),
('onboarding X new clients in Y months','metric','onboarding 4 new clients in 6 months',8),
('training X staff members','metric','training 7 staff members on system use',7),
('reaching X farming households','metric','reaching 2,400 farming households',8),
('covering X sub-counties','metric','covering 6 sub-counties in Turkana',8),
('reducing response time from X to Y','metric','reducing response time from 3 days to 4 hours',8),
('increasing yield by roughly X%','metric','increasing yield by roughly 28%',8),
('reducing water waste by X litres/day','metric','reducing water waste by ~800 litres per day',7),
('completing X projects on time','metric','completing 6 projects on time and within budget',8),
('managing a budget of KES X','metric','managing a budget of KES 1.2M',7),

-- APPROXIMATE — Honest Estimates
('reducing X by roughly Y%','approximate','reducing water usage by roughly 14%',9),
('improving X by approximately Y%','approximate','improving efficiency by approximately 20%',8),
('cutting X by about Y%','approximate','cutting costs by about 15%',8),
('saving roughly KES X per month','approximate','saving roughly KES 50K per month',8),
('reducing X by around Y%','approximate','reducing errors by around 30%',7),
('roughly X times faster','approximate','roughly 3 times faster than the previous process',8),
('estimated X% improvement','approximate','estimated 25% improvement in water distribution',7),

-- EM-DASH — Punchy Human Results
('— zero X across Y months','emdash','— zero missed deadlines across 6 months',9),
('— X clients, zero complaints','emdash','— 8 clients, zero complaints in 18 months',9),
('— delivered on time, every time','emdash','— delivered on time, every time',8),
('— no escalations in Y months','emdash','— no escalations in 8 months',8),
('— first engineer on site, last to leave','emdash','— first engineer on site, last to leave',9),
('— resolved without escalating','emdash','— resolved without escalating to management',9),
('— still running 18 months later','emdash','— still running 18 months later without modification',8),
('— zero rework required','emdash','— zero rework required after handover',8),
('— adopted as standard across the team','emdash','— adopted as standard process across the team',8),
('— county adopted it as official procedure','emdash','— county adopted it as official assessment procedure',8),

-- QUALITATIVE — No Numbers Needed
('which noticeably improved client satisfaction','qualitative','which noticeably improved client satisfaction',8),
('making a measurable difference on site','qualitative','making a measurable difference on site',8),
('which the team adopted within a week','qualitative','which the team adopted within a week',8),
('consistently praised by clients','qualitative','consistently praised by clients in feedback sessions',7),
('which reduced pressure on the field team','qualitative','which reduced pressure on the field team significantly',7),
('well received by county stakeholders','qualitative','well received by county government and NGO stakeholders',7),
('clients specifically requested repeat work','qualitative','clients specifically requested repeat installations',8),
('county government used findings in planning','qualitative','county government used findings in drought response planning',8),
('flagged early enough to prevent failure','qualitative','flagged early enough to prevent system failure',8),
('which freed up the team for higher priority work','qualitative','which freed up the team for higher priority site work',7),

-- NONE — Bullet ends cleanly without result
('','none','Designed drip irrigation systems for 8 farms in Central Kenya.',9),
('','none','Mapped soil moisture levels across the project catchment area.',8),
('','none','Coordinated weekly site visits across Nairobi and Kiambu counties.',8),
('','none','Prepared monthly drought bulletins for county government distribution.',8),
('','none','Trained 12 farm operators on drip system maintenance procedures.',8);

-- ─── block 5/6 ────────────────────────────────
INSERT OR IGNORE INTO cv_openers (opener, type, triggers_comma, example, length_type) VALUES

-- NONE — Start directly with verb (most common)
('','none',false,'Designed drip systems for 8 farms.','short'),
('','none',false,'Managed a portfolio of 8 enterprise clients.','medium'),
('','none',false,'Led the irrigation upgrade across 3 counties.','long'),

-- CONTEXT
('Working across X counties,','context',true,'Working across 3 counties, coordinated drought plans.','medium'),
('Based in X,','context',true,'Based in Nairobi, managed accounts across Central Kenya.','medium'),
('Covering X client accounts,','context',true,'Covering 8 accounts, delivered zero missed deadlines.','medium'),
('Across X project sites,','context',true,'Across 6 sites, standardized the soil sampling process.','medium'),
('Serving X enterprise clients,','context',true,'Serving 8 enterprise clients, maintained 97% uptime.','medium'),
('Supporting X NGO partners,','context',true,'Supporting 5 NGO partners, coordinated drought response.','medium'),
('Across X sub-counties,','context',true,'Across 6 sub-counties, collected early warning data.','medium'),
('For X farming households,','context',true,'For 2,400 farming households, implemented drought plans.','medium'),
('Covering X hectares,','context',true,'Covering 40 hectares, maintained drip system efficiency.','medium'),

-- TIME
('During peak drought season,','time',true,'During peak drought season, coordinated early warning collection.','long'),
('Over X months,','time',true,'Over 6 months, reduced water waste by roughly 14%.','medium'),
('Within the first X weeks,','time',true,'Within the first 3 weeks, identified 2 critical failures.','medium'),
('By end of quarter,','time',true,'By end of quarter, onboarded 4 new enterprise clients.','medium'),
('Over X consecutive quarters,','time',true,'Over 3 consecutive quarters, hit all delivery targets.','medium'),
('Within X days of joining,','time',true,'Within 2 weeks of joining, resolved a backlogged site issue.','medium'),
('During the X-month pilot,','time',true,'During the 6-month pilot, tracked outcomes for 8 farms.','medium'),

-- SITUATION
('With limited field resources,','situation',true,'With limited field resources, built monitoring process from scratch.','long'),
('As the only engineer on site,','situation',true,'As the only engineer on site, resolved 3 pump failures.','long'),
('Despite supply chain delays,','situation',true,'Despite supply chain delays, delivered the system on schedule.','long'),
('Amid drought conditions,','situation',true,'Amid drought conditions, maintained 99% system uptime.','long'),
('Under tight deadlines,','situation',true,'Under tight deadlines, completed design 2 days early.','medium'),
('With no prior documentation,','situation',true,'With no prior documentation, rebuilt the system specs from scratch.','long'),
('Following a system failure,','situation',true,'Following a system failure, diagnosed and restored operations in 4 hours.','long'),
('After inheriting the project,','situation',true,'After inheriting the project midway, delivered on the original deadline.','long'),
('Without additional budget,','situation',true,'Without additional budget, achieved the same outcome using existing resources.','long'),

-- ACHIEVEMENT
('As sole engineer on the project,','achievement',true,'As sole engineer, shipped the v2 redesign on time.','long'),
('First contact for client escalations,','achievement',false,'First contact for escalations — resolved 4 without escalating.','long'),
('Recognized as top performer,','achievement',false,'Recognized as top performer — led 3 of the 5 highest-value projects.','long'),
('Clients specifically requested,','achievement',false,'Clients specifically requested repeat installations — 5 times in 18 months.','long'),
('Promoted ahead of schedule,','achievement',false,'Promoted ahead of schedule after delivering 3 consecutive early projects.','long');

-- ─── block 6/6 ────────────────────────────────
INSERT OR IGNORE INTO cv_context_connectors (connector, type, example) VALUES

-- LOCATION
('across Nairobi and Central Kenya','location','Managed accounts across Nairobi and Central Kenya'),
('across X counties in Kenya','location','Surveyed sites across 4 counties in Kenya'),
('across the Rift Valley and Western Kenya','location','Coordinated teams across the Rift Valley'),
('across X project sites','location','Monitored conditions across 6 project sites'),
('in X county','location','Implemented drought plans in Turkana County'),
('for smallholder farmers in X region','location','Designed systems for farmers in Central Kenya'),
('across Northern Kenya','location','Coordinated programs across Northern Kenya'),
('across X arid and semi-arid counties','location','Assessed conditions across 4 ASAL counties'),
('from Nairobi to the coast','location','Managed client accounts from Nairobi to the coast'),
('across East Africa','location','Delivered irrigation solutions across East Africa'),

-- TEAM
('coordinating with a X-person field team','team','coordinating with a 5-person field team'),
('working alongside X senior engineers','team','working alongside 2 senior engineers'),
('as part of a X-person project team','team','as part of a 4-person project team'),
('supporting a cross-functional team of X','team','supporting a cross-functional team of 6'),
('leading a team of X technicians','team','leading a team of 3 technicians'),
('with X government and NGO partners','team','with 8 government and NGO partners'),
('alongside county government officials','team','alongside county government officials'),
('with X field officers','team','with 5 field officers across 3 sub-counties'),

-- SCOPE
('covering X enterprise client accounts','scope','covering 8 enterprise client accounts'),
('across X hectares of farmland','scope','across 40 hectares of farmland'),
('for X farming households','scope','for 120 farming households'),
('supporting X NGO partners','scope','supporting 5 NGO partner organizations'),
('across X sub-counties','scope','across 6 sub-counties'),
('for X smallholder farms','scope','for 15 smallholder farms'),
('across X irrigation schemes','scope','across 4 irrigation schemes'),
('covering X beneficiaries','scope','covering 2,400 beneficiaries'),
('across X water points','scope','across 12 water points'),
('for X county government departments','scope','for 3 county government departments'),

-- TIME
('over X months','time','over 9 months'),
('within a X-week turnaround','time','within a 3-week turnaround'),
('during a X-month pilot','time','during a 6-month pilot program'),
('across X consecutive quarters','time','across 3 consecutive quarters'),
('in under X weeks','time','in under 2 weeks'),
('ahead of the X-month deadline','time','ahead of the 3-month deadline'),
('within the first X days','time','within the first 14 days'),
('over X growing seasons','time','over 2 growing seasons'),

-- CONDITION
('despite supply chain delays','condition','despite supply chain delays'),
('under tight budget constraints','condition','under tight budget constraints'),
('amid drought conditions','condition','amid drought conditions'),
('with limited field resources','condition','with limited field resources'),
('during peak farming season','condition','during peak farming season'),
('without additional headcount','condition','without additional headcount'),
('under emergency response timelines','condition','under emergency response timelines'),
('with zero prior documentation','condition','with zero prior documentation'),
('despite competing project priorities','condition','despite competing project priorities'),
('in a first-of-its-kind implementation','condition','in a first-of-its-kind county implementation');
