import { GoogleGenAI, Type } from "@google/genai";
import type { UserProfile, CVData } from '../types';

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const { profile, jobDescription, enableEnhancements } = req.body as { profile: UserProfile, jobDescription: string, enableEnhancements: boolean };
    if (!profile || !jobDescription) {
        return res.status(400).json({ error: 'User profile and job description are required.' });
    }

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    let experienceInstruction: string;
    let projectsInstruction: string;
    let cvDataSchema: any;
    let githubInstruction = '';

    if (profile.personalInfo.github) {
        githubInstruction = `IMPORTANT: The user has provided a GitHub profile: ${profile.personalInfo.github}. Analyze their repositories to infer key technologies, projects, and programming languages they are proficient in. Use this information to enrich the skills and projects sections, making them more authentic and detailed.`;
    }

    const baseExperienceItems = {
        type: Type.OBJECT,
        properties: {
            company: { type: Type.STRING },
            jobTitle: { type: Type.STRING },
            dates: { type: Type.STRING, description: "e.g., 'Jan 2020 - Present'" },
            responsibilities: {
                type: Type.ARRAY,
                description: "3-5 bullet points of key achievements and responsibilities, tailored to the job description.",
                items: { type: Type.STRING }
            }
        },
        required: ["company", "jobTitle", "dates", "responsibilities"]
    };

    const baseProjectItems = {
        type: Type.OBJECT,
        properties: {
            name: { type: Type.STRING },
            description: { type: Type.STRING },
            link: { type: Type.STRING, description: "A plausible URL for the project, e.g., a GitHub repo or live website."}
        },
        required: ["name", "description"]
    };
    
    const baseSchemaProperties = {
        summary: {
            type: Type.STRING,
            description: "A professional summary tailored to the job description, 2-4 sentences long."
        },
        skills: {
            type: Type.ARRAY,
            description: "A list of the most relevant skills for the job, generated by analyzing the job description and referencing the user's skills.",
            items: { type: Type.STRING }
        },
        education: {
            type: Type.ARRAY,
            items: {
                type: Type.OBJECT,
                properties: {
                    degree: { type: Type.STRING },
                    school: { type: Type.STRING },
                    year: { type: Type.STRING, description: "Graduation year" },
                    description: { type: Type.STRING, description: "A brief, 1-2 sentence description of the course or degree program."}
                },
                required: ["degree", "school", "year"]
            }
        },
        languages: {
            type: Type.ARRAY,
            description: "A list of languages and the user's proficiency.",
            items: {
                type: Type.OBJECT,
                properties: {
                    name: { type: Type.STRING },
                    proficiency: { type: Type.STRING }
                },
                required: ["name", "proficiency"]
            }
        },
    };

    if (enableEnhancements) {
        experienceInstruction = `3.  **Generated Experience**: Invent ONE or TWO additional, highly plausible, fictional work experience entries that would make the user the IDEAL candidate for this role. These entries should be creative, impressive, and directly relevant to the job description. For the company names, be highly creative and industry-specific. You can use names of real, plausible-sounding companies (e.g., smaller tech consultancies, startups) or create fictional names that sound authentic and professional, such as 'Innovatech Solutions', 'Quantum Dynamics Corp', or 'Synergy Systems Inc'. Be specific with project details and technical achievements. Place these new entries at the TOP of the experience list.`;
        projectsInstruction = `6.  **Projects**: Generate 1-2 fictional but realistic project examples that would be impressive for this role. Include a brief description and plausible-looking GitHub or website links for each. If the user provided projects, you can ignore them in favor of these newly generated, more relevant ones.`;
        
        cvDataSchema = {
        type: Type.OBJECT,
        properties: { ...baseSchemaProperties,
            experience: { type: Type.ARRAY, items: baseExperienceItems },
            projects: { type: Type.ARRAY, items: baseProjectItems }
        },
        required: ["summary", "experience", "skills", "education", "languages"]
        };

    } else {
        experienceInstruction = `3.  **Experience**: Use ONLY the work experience provided by the user. Do not invent any new jobs. Rewrite the bullet points to use strong action verbs and quantify achievements where possible. Emphasize the experience most relevant to the job. Include ALL of the user's original experiences.`;
        projectsInstruction = `6.  **Projects**: Use ONLY the projects provided by the user. If the user provided projects, rephrase their descriptions to better align with the job. If the user did not provide any projects, this section can be omitted from the output. Do not invent new projects.`;
        
        cvDataSchema = {
        type: Type.OBJECT,
        properties: { ...baseSchemaProperties,
            experience: { type: Type.ARRAY, items: baseExperienceItems },
            projects: { type: Type.ARRAY, items: baseProjectItems }
        },
        required: ["summary", "experience", "skills", "education", "languages"]
        };
    }

    const prompt = `
        You are a professional CV writer and career coach. Your task is to create a tailored CV based on the provided user profile and job description.
        USER PROFILE: ${JSON.stringify(profile, null, 2)}
        JOB DESCRIPTION: ${jobDescription}
        ${githubInstruction}
        Instructions:
        1. Summary: Rewrite the professional summary to be concise, powerful, and perfectly aligned with the job description.
        2. User's Experience: Review all of the user's provided work experience. For each entry, rewrite the bullet points to use strong action verbs and quantify achievements where possible. Emphasize the experience most relevant to the job. Include ALL of the user's original experiences.
        ${experienceInstruction}
        4. Skills: Generate a list of skills that are most relevant to the job description. Use the user's skills list as a reference but DO NOT be limited by it. Create the best possible skill list for this specific job.
        5. Education: For each education entry, add a brief, 1-2 sentence 'description' of the degree program.
        ${projectsInstruction}
        7. Languages: Include the languages provided by the user. Do not invent new ones.
        8. Overall: Ensure the entire CV is professional, ATS-friendly, and free of errors.
        9. Return ONLY the JSON object adhering to the provided schema.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: { responseMimeType: 'application/json', responseSchema: cvDataSchema, temperature: 0.6 }
    });

    const cvData: CVData = JSON.parse(response.text.trim());
    res.status(200).json(cvData);
  } catch (error) {
    console.error("Error in /api/generate-cv:", error);
    res.status(500).json({ error: "Failed to generate CV. The AI model may be overloaded." });
  }
}
